# Generated by Django 5.0.6 on 2024-08-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bf', models.IntegerField()),
                ('lu', models.IntegerField()),
                ('di', models.IntegerField()),
                ('cal', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('pro', models.IntegerField()),
                ('sug', models.IntegerField()),
                ('imagepath', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
