# Generated by Django 5.0.6 on 2024-08-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='pro',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='sug',
            field=models.FloatField(),
        ),
    ]
