# Generated by Django 5.0.6 on 2024-09-20 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='blocklist',
            name='unique_block_pairs',
        ),
        migrations.AddConstraint(
            model_name='blocklist',
            constraint=models.UniqueConstraint(condition=models.Q(('blocking_status', False)), fields=('blocker_id', 'blocked_id'), name='unique_block_pairs'),
        ),
    ]
