# Generated by Django 5.0.6 on 2024-09-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_remove_blocklist_unique_block_pairs_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='blocklist',
            name='unique_block_pairs',
        ),
    ]
