# Generated by Django 5.0.6 on 2024-09-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_remove_blocklist_unique_block_pairs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocklist',
            old_name='blocked_id',
            new_name='blocked',
        ),
        migrations.RenameField(
            model_name='blocklist',
            old_name='blocker_id',
            new_name='blocker',
        ),
    ]
