# Generated by Django 5.0.6 on 2024-08-12 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatrooms_users_chatroom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatrooms_users',
            name='chatroom',
        ),
        migrations.RemoveField(
            model_name='chatrooms_users',
            name='user',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_2', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(fields=('user_1', 'user_2'), name='unique_users'),
        ),
        migrations.DeleteModel(
            name='Chatrooms_Users',
        ),
    ]
