# Generated by Django 5.0.6 on 2024-08-12 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chatrooms_users_chatroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chatroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom'),
            preserve_default=False,
        ),
    ]
