# Generated by Django 5.0.6 on 2024-07-09 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_post_created_at'),
        ('gym', '0007_alter_shifts_shift_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postering', to='gym.employee'),
        ),
    ]
