# Generated by Django 5.0.6 on 2024-07-09 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_post_poster'),
        ('gym', '0007_alter_shifts_shift_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='gym.employee'),
        ),
    ]
