# Generated by Django 5.0.6 on 2024-07-09 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_post_poster'),
        ('gym', '0007_alter_shifts_shift_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approved_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='approved', to='gym.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='gym.gym'),
            preserve_default=False,
        ),
    ]
