# Generated by Django 5.0.6 on 2024-07-09 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_post_approved_by_post_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='community.post'),
            preserve_default=False,
        ),
    ]
