# Generated by Django 5.0.6 on 2024-09-08 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_alter_comments_comment'),
        ('user', '0014_goal_activity_level_goal_calories_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', 'like'), ('dislike', 'dislike'), ('laugh', 'laugh'), ('surprise', 'surprise'), ('confused', 'confused')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='user.client')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='community.post')),
            ],
        ),
        migrations.DeleteModel(
            name='likes',
        ),
    ]
