# Generated by Django 5.0.6 on 2024-09-08 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_reactions_delete_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like_count',
            new_name='reaction_count',
        ),
    ]
