# Generated by Django 5.0.6 on 2024-09-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_comments_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactions',
            name='reaction',
            field=models.CharField(choices=[('like', 'like'), ('dislike', 'dislike'), ('laugh', 'laugh'), ('surprise', 'surprise'), ('confused', 'confused')], max_length=10),
        ),
    ]
