# Generated by Django 5.0.6 on 2024-08-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vouchers', '0002_voucher_restrict_num_using_redeem'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeem',
            name='code',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
    ]
