# Generated by Django 5.0.6 on 2024-08-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vouchers', '0004_voucher_discount_alter_voucher_number_of_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redeem',
            name='created_at',
        ),
    ]
