# Generated by Django 5.0.6 on 2024-07-21 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0007_remove_classes_clients_remove_classes_days_of_week_and_more'),
        ('gym', '0016_gym_allowed_days_for_registraiton_cancellation_and_more'),
        ('store', '0014_rename_falvor_supplements_flavor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('image_path', models.ImageField(blank=True, upload_to='images/')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Percentage_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_cut', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='store.category')),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='percentage_offers', to='classes.classes')),
                ('fee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='percentage_offers', to='gym.registration_fee')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percentage_offers', to='offers.offer')),
                ('supp_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='store.supplements_category')),
            ],
        ),
        migrations.CreateModel(
            name='Price_Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_offers', to='offers.offer')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectHasPriceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_offers', to='gym.registration_fee')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='store.branch_products')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='offers.price_offer')),
            ],
        ),
    ]
