# Generated by Django 5.0.6 on 2024-07-21 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_percentage_offer_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_offer',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_offers', to='offers.offer'),
        ),
    ]
