# Generated by Django 5.0.6 on 2024-07-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offer_end_date_alter_offer_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecthaspriceoffer',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
