# Generated by Django 5.0.6 on 2024-07-22 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0016_gym_allowed_days_for_registraiton_cancellation_and_more'),
        ('offers', '0005_objecthaspriceoffer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='branch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='gym.branch'),
            preserve_default=False,
        ),
    ]
