# Generated by Django 5.0.6 on 2024-08-01 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_alter_class_scheduel_trainer'),
        ('gym', '0018_trainer_online_trainine_price_and_more'),
        ('offers', '0008_alter_percentage_offer_category_and_more'),
        ('store', '0015_product_brand_product_image_path_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentage_offer',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='store.category'),
        ),
        migrations.AlterField(
            model_name='percentage_offer',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='percentage_offers', to='classes.class_scheduel'),
        ),
        migrations.AlterField(
            model_name='percentage_offer',
            name='fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='percentage_offers', to='gym.registration_fee'),
        ),
        migrations.AlterField(
            model_name='percentage_offer',
            name='supp_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='store.supplements_category'),
        ),
    ]
