# Generated by Django 5.0.6 on 2024-08-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_alter_percentage_offer_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='image_path',
        ),
    ]
