# Generated by Django 5.0.6 on 2024-08-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_remove_offer_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentage_offer',
            name='code',
            field=models.CharField(null=True),
        ),
    ]
