# Generated by Django 5.0.6 on 2024-08-30 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_percentage_offer_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percentage_offer',
            name='code',
        ),
    ]
