# Generated by Django 5.0.6 on 2024-09-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0027_gym_allowed_number_for_update'),
        ('offers', '0012_remove_percentage_offer_code'),
        ('store', '0019_accessories_product_color_size'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='objecthaspriceoffer',
            constraint=models.UniqueConstraint(fields=('product', 'offer'), name='product_offer_constraint'),
        ),
    ]
