# Generated by Django 5.0.6 on 2024-08-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0026_remove_gym_current_number_of_clients_and_more'),
        ('gym_sessions', '0001_initial'),
        ('user', '0014_goal_activity_level_goal_calories_required_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gym_Subscribtion',
            new_name='Gym_Subscription',
        ),
    ]
