# Generated by Django 5.0.6 on 2024-08-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_sessions', '0002_rename_gym_subscribtion_gym_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym_subscription',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
