# Generated by Django 5.0.6 on 2024-08-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_sessions', '0003_alter_gym_subscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym_subscription',
            name='price_offer',
            field=models.FloatField(null=True),
        ),
    ]
