# Generated by Django 5.0.6 on 2024-08-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_sessions', '0004_gym_subscription_price_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym_subscription',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
