# Generated by Django 5.0.6 on 2024-08-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_sessions', '0005_alter_gym_subscription_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_sessions',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
