# Generated by Django 5.0.6 on 2024-08-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_sessions', '0006_alter_branch_sessions_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_sessions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
