# Generated by Django 5.0.6 on 2024-09-22 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_sessions', '0008_branch_sessions_end_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_sessions',
            name='end_session',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 18, 39, 25, 346188), null=True),
        ),
    ]
