# Generated by Django 5.0.6 on 2024-07-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='hall',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
