# Generated by Django 5.0.6 on 2024-07-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classes_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
