# Generated by Django 5.0.6 on 2024-07-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_classes_end_date_alter_classes_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
