# Generated by Django 5.0.6 on 2024-07-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_classes_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='image_path',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
