# Generated by Django 5.0.6 on 2024-07-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_classes_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
