# Generated by Django 5.0.6 on 2024-07-21 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_classes_points'),
        ('gym', '0016_gym_allowed_days_for_registraiton_cancellation_and_more'),
        ('user', '0005_client_qr_code_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='days_of_week',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='trainer',
        ),
        migrations.AlterField(
            model_name='classes',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='gym.branch'),
        ),
        migrations.CreateModel(
            name='Class_Scheduel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
                ('days_of_week', models.JSONField(default=dict)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('hall', models.IntegerField(blank=True)),
                ('allowed_number_for_class', models.IntegerField(default=0)),
                ('allowed_days_to_cancel', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduel', to='classes.classes')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='gym.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Client_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retieved_money', models.IntegerField(default=0)),
                ('retrieved_reason', models.CharField(max_length=40)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='classes.class_scheduel')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='user.client')),
            ],
        ),
    ]
