# Generated by Django 5.0.6 on 2024-07-22 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_remove_classes_clients_remove_classes_days_of_week_and_more'),
        ('gym', '0016_gym_allowed_days_for_registraiton_cancellation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_scheduel',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='gym.trainer'),
        ),
    ]
