# Generated by Django 5.0.6 on 2024-08-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_alter_class_scheduel_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_class',
            name='retrieved_reason',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
