# Generated by Django 5.0.6 on 2024-09-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_alter_client_class_retrieved_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_scheduel',
            name='current_number_of_trainees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client_class',
            name='retieved_money',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
