# Generated by Django 5.0.6 on 2024-09-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_class_scheduel_current_number_of_trainees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_class',
            name='retieved_money',
            field=models.FloatField(default=0, null=True),
        ),
    ]
