# Generated by Django 5.0.6 on 2024-09-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_alter_client_class_retieved_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_class',
            name='offered_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='client_class',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
