# Generated by Django 5.0.6 on 2024-07-04 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
                ('goal', models.CharField(max_length=50)),
                ('goal_weight', models.FloatField(default=0.0)),
                ('required_protien', models.FloatField(default=0.0)),
                ('required_carbs', models.FloatField(default=0.0)),
                ('required_fats', models.FloatField(default=0.0)),
                ('required_calories', models.FloatField(default=0.0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='user.client')),
            ],
        ),
    ]
