# Generated by Django 5.0.6 on 2024-06-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_something'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='height',
            field=models.FloatField(default=0.0),
        ),
    ]
