# Generated by Django 5.0.6 on 2024-07-12 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_history_created_at_history_predicted_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
                ('goal', models.CharField(max_length=50)),
                ('goal_weight', models.FloatField(default=0.0)),
                ('predicted_date', models.DateField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='user.client')),
            ],
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
