# Generated by Django 5.0.6 on 2024-07-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_goal_delete_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='qr_code_image',
            field=models.ImageField(null=True, upload_to='qr_codes'),
        ),
    ]
