# Generated by Django 5.0.6 on 2024-07-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_client_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image_path',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
