# Generated by Django 5.0.6 on 2024-07-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_client_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
