# Generated by Django 5.0.6 on 2024-07-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_goal_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='number_updates',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
