# Generated by Django 5.0.6 on 2024-07-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_goal_number_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='achieved_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='number_updates',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
