# Generated by Django 5.0.6 on 2024-07-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_goal_achieved_weight_alter_goal_number_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
