# Generated by Django 5.0.6 on 2024-08-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_goal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='wakeup_time',
        ),
    ]
