# Generated by Django 5.0.6 on 2024-08-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_client_wakeup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='activity_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Low', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='calories_required',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='goal',
            name='fats_required',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='goal',
            name='protein_required',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
