# Generated by Django 5.0.6 on 2024-09-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_goal_activity_level_goal_calories_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='app_rate',
        ),
    ]
