# Generated by Django 5.0.6 on 2024-08-01 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0018_trainer_online_trainine_price_and_more'),
        ('user', '0012_alter_goal_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealsSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MealsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Brunch', 'Brunch'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack'), ('Pre-Workout', 'Pre-Workout'), ('Post-Workout', 'Post-Workout')], max_length=50)),
                ('meals_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals_types', to='nutrition.mealsschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('portion_size', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('portion_unit', models.CharField(max_length=20)),
                ('meals_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.mealstype')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('protein_required', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('carbs_required', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fats_required', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('calories_required', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('weeks_number', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to='user.client')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to='gym.trainer')),
            ],
        ),
        migrations.AddField(
            model_name='mealsschedule',
            name='nutrition_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals_schedules', to='nutrition.nutritionplan'),
        ),
        migrations.AddConstraint(
            model_name='mealstype',
            constraint=models.UniqueConstraint(fields=('meals_schedule', 'type'), name='unique_meal_per_day'),
        ),
        migrations.AddConstraint(
            model_name='meals',
            constraint=models.UniqueConstraint(fields=('meals_type', 'name'), name='unique_meal_per_type'),
        ),
        migrations.AddConstraint(
            model_name='mealsschedule',
            constraint=models.UniqueConstraint(fields=('nutrition_plan', 'day'), name='unique_day_per_week'),
        ),
    ]
