# Generated by Django 5.0.6 on 2024-08-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionplan',
            name='is_same',
            field=models.BooleanField(default=False),
        ),
    ]
