# Generated by Django 5.0.6 on 2024-08-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_mealsschedule_same_as_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
