# Generated by Django 5.0.6 on 2024-08-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_meals_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='is_deleted',
        ),
    ]
