# Generated by Django 5.0.6 on 2024-08-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_meals_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealstype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
