# Generated by Django 5.0.6 on 2024-08-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_mealstype_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionplan',
            name='calories_required',
        ),
        migrations.RemoveField(
            model_name='nutritionplan',
            name='carbs_required',
        ),
        migrations.RemoveField(
            model_name='nutritionplan',
            name='fats_required',
        ),
        migrations.RemoveField(
            model_name='nutritionplan',
            name='protein_required',
        ),
    ]
