# Generated by Django 5.0.6 on 2024-07-31 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0017_remove_equipment_exercise_unique_exercises_equipments_and_more'),
        ('user', '0012_alter_goal_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client_Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease', to='user.client')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='disease.disease')),
            ],
        ),
        migrations.CreateModel(
            name='Limitations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='disease.disease')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease', to='equipments.equipment')),
            ],
        ),
    ]
