# Generated by Django 5.0.6 on 2024-08-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
        ('equipments', '0020_diagram_branch_floor_and_more'),
        ('user', '0014_goal_activity_level_goal_calories_required_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='client_disease',
            constraint=models.UniqueConstraint(fields=('client', 'disease'), name='unique_client_disease'),
        ),
        migrations.AddConstraint(
            model_name='limitations',
            constraint=models.UniqueConstraint(fields=('equipment', 'disease'), name='unique_equipment_disease'),
        ),
    ]
