# Generated by Django 5.0.6 on 2024-08-26 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_client_disease_unique_client_disease_and_more'),
        ('equipments', '0022_alter_equipment_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='limitations',
            name='unique_equipment_disease',
        ),
        migrations.RemoveField(
            model_name='limitations',
            name='equipment',
        ),
        migrations.AddField(
            model_name='limitations',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disease', to='equipments.exercise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='limitations',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='disease.disease'),
        ),
        migrations.AddConstraint(
            model_name='limitations',
            constraint=models.UniqueConstraint(fields=('exercise', 'disease'), name='unique_exercise_disease'),
        ),
    ]
