# Generated by Django 5.0.6 on 2024-08-26 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0003_remove_limitations_unique_equipment_disease_and_more'),
        ('equipments', '0022_alter_equipment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitations',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease', to='equipments.equipment_exercise'),
        ),
    ]
