# Generated by Django 5.0.6 on 2024-07-26 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0014_disease_limitations'),
        ('gym', '0017_trainer_session_period'),
        ('user', '0005_client_qr_code_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gym_Training_plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_duration_weeks', models.IntegerField(default=0)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gymPlans', to='gym.gym')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planGym', to='plans.training_plan')),
            ],
        ),
        migrations.CreateModel(
            name='Gym_plans_Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gymPlans', to='user.client')),
                ('gym_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='plans.training_plan')),
            ],
        ),
        migrations.CreateModel(
            name='Client_TrianingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientsPlans', to='gym.trainer')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PrivateTrainingPlans', to='user.client')),
                ('training_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='TrainersClientsPlans', to='plans.training_plan')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_rest', models.BooleanField(default=False)),
                ('has_cardio', models.BooleanField(default=True)),
                ('cardio_durations', models.TimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='plans.training_plan')),
            ],
        ),
        migrations.CreateModel(
            name='Workout_Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(default=0)),
                ('reps', models.JSONField(default=dict)),
                ('rest_time_seconds', models.TimeField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='equipments.equipment_exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='plans.workout')),
            ],
        ),
    ]
