# Generated by Django 5.0.6 on 2024-07-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_workout_exercises_rest_time_seconds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gym_plans_clients',
            old_name='gym_plan',
            new_name='gym_training_plan',
        ),
        migrations.RenameField(
            model_name='gym_training_plans',
            old_name='plan',
            new_name='training_plan',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='plan',
            new_name='training_plan',
        ),
    ]
