# Generated by Django 5.0.6 on 2024-07-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_rename_gym_plan_gym_plans_clients_gym_training_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='cardio_durations',
        ),
        migrations.AddField(
            model_name='workout',
            name='cardio_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
