# Generated by Django 5.0.6 on 2024-07-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0015_diagram_height_diagram_width'),
        ('plans', '0004_remove_workout_cardio_durations_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.UniqueConstraint(fields=('training_plan', 'order'), name='unique_order_plan'),
        ),
        migrations.AddConstraint(
            model_name='workout_exercises',
            constraint=models.UniqueConstraint(fields=('workout', 'order'), name='unique_order_workout'),
        ),
    ]
