# Generated by Django 5.0.6 on 2024-07-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_workout_unique_order_plan_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workout',
            name='unique_order_plan',
        ),
    ]
