# Generated by Django 5.0.6 on 2024-07-28 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_remove_workout_unique_order_plan'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workout_exercises',
            name='unique_order_workout',
        ),
    ]
