# Generated by Django 5.0.6 on 2024-08-01 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0018_trainer_online_trainine_price_and_more'),
        ('plans', '0008_alter_gym_training_plans_plan_duration_weeks_and_more'),
        ('user', '0012_alter_goal_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Trianing_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PrivateTrainingPlans', to='user.client')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientsPlans', to='gym.trainer')),
                ('training_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='TrainersClientsPlans', to='plans.training_plan')),
            ],
        ),
        migrations.DeleteModel(
            name='Client_TrianingPlan',
        ),
    ]
