# Generated by Django 5.0.6 on 2024-08-01 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0018_trainer_online_trainine_price_and_more'),
        ('plans', '0009_client_trianing_plan_delete_client_trianingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_trianing_plan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client_trianing_plan',
            name='plan_duration_weeks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gym_plans_clients',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gym_training_plans',
            name='gym',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gymPlans', to='gym.gym'),
        ),
    ]
