# Generated by Django 5.0.6 on 2024-08-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_alter_client_trianing_plan_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_trianing_plan',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
