# Generated by Django 5.0.6 on 2024-08-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0020_diagram_branch_floor_and_more'),
        ('gym', '0020_rename_online_trainine_price_trainer_online_training_price'),
        ('plans', '0012_alter_client_trianing_plan_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='same_as_order',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='gym_training_plans',
            constraint=models.UniqueConstraint(fields=('training_plan', 'gym'), name='training_plan_gym'),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.UniqueConstraint(fields=('training_plan', 'name', 'order'), name='unique_workout_name_order'),
        ),
        migrations.AddConstraint(
            model_name='workout_exercises',
            constraint=models.UniqueConstraint(fields=('workout', 'exercise', 'order'), name='unique_workout_exercise_order'),
        ),
    ]
