# Generated by Django 5.0.6 on 2024-08-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0013_workout_same_as_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='has_cardio',
            field=models.BooleanField(default=False),
        ),
    ]
