# Generated by Django 5.0.6 on 2024-08-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0015_alter_gym_plans_clients_gym_training_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym_plans_clients',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
