# Generated by Django 5.0.6 on 2024-07-05 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_alter_shifts_shift_type'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('price', models.FloatField(default=0.0)),
                ('points_gained', models.IntegerField(default=0)),
                ('image_path', models.ImageField(null=True, upload_to='images/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_for_branch', to='gym.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_product', to='store.product')),
            ],
        ),
    ]
