# Generated by Django 5.0.6 on 2024-07-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_alter_shifts_shift_type'),
        ('store', '0002_gym_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gym_product',
            new_name='Branch_product',
        ),
    ]
