# Generated by Django 5.0.6 on 2024-07-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_gym_product_branch_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_product',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
