# Generated by Django 5.0.6 on 2024-07-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_branch_product_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch_product',
            name='is_public',
        ),
    ]
