# Generated by Django 5.0.6 on 2024-07-14 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_remove_gym_regestration_price'),
        ('store', '0005_remove_branch_product_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_path',
        ),
        migrations.AddField(
            model_name='branch_product',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='branch_product',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch_product',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='gym.branch'),
        ),
        migrations.AlterField(
            model_name='branch_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='store.product'),
        ),
        migrations.DeleteModel(
            name='Accessories',
        ),
    ]
