# Generated by Django 5.0.6 on 2024-07-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_supplements_servings_supplements_caffeine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplements',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
