# Generated by Django 5.0.6 on 2024-07-15 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_supplements_calories_supplements_flavour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplements',
            name='product',
        ),
        migrations.RemoveField(
            model_name='supplements',
            name='supplement_category',
        ),
        migrations.RemoveField(
            model_name='branch_product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='branch_product',
            name='size',
        ),
        migrations.AlterField(
            model_name='branch_product',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.FloatField(default=0.0, null=True)),
                ('carbs', models.FloatField(default=0.0, null=True)),
                ('calories', models.FloatField(default=0.0, null=True)),
                ('caffeine', models.FloatField(default=0.0, null=True)),
                ('weight', models.FloatField(default=0.0, null=True)),
                ('flavor', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(max_length=50, null=True)),
                ('size', models.CharField(max_length=50, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
                ('supplement_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplemetns', to='store.supplements_category')),
            ],
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='Supplements',
        ),
    ]
