# Generated by Django 5.0.6 on 2024-07-15 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_supplements_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch_product',
            name='product',
        ),
        migrations.AddField(
            model_name='branch_product',
            name='variant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='store.variants'),
            preserve_default=False,
        ),
    ]
