# Generated by Django 5.0.6 on 2024-07-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_branch_product_product_branch_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='flavor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
