# Generated by Django 5.0.6 on 2024-07-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_variants_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplements',
            old_name='falvor',
            new_name='flavor',
        ),
    ]
