# Generated by Django 5.0.6 on 2024-08-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_brand_product_image_path_alter_product_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'brand', 'category'), name='brand_category_name_constraint'),
        ),
    ]
