# Generated by Django 5.0.6 on 2024-08-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0018_trainer_online_trainine_price_and_more'),
        ('store', '0016_product_brand_category_name_constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='branch_products',
            constraint=models.UniqueConstraint(fields=('branch', 'product_id', 'product_type'), name='branch_product_constraint'),
        ),
    ]
