# Generated by Django 5.0.6 on 2024-08-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_meals_product_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='accessories',
            constraint=models.UniqueConstraint(fields=('product', 'color', 'size'), name='product_color_size'),
        ),
    ]
