# Generated by Django 5.0.6 on 2024-08-26 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0011_percentage_offer_code'),
        ('store', '0019_accessories_product_color_size'),
        ('user', '0014_goal_activity_level_goal_calories_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0.0)),
                ('offered_total', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='user.client')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_PriceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('price_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='offers.price_offer')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PriceOffers', to='purchasing.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='store.branch_products')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='purchasing.purchase')),
            ],
        ),
        migrations.AddConstraint(
            model_name='purchase_priceoffer',
            constraint=models.UniqueConstraint(fields=('purchase', 'price_offer'), name='purchase_price_offer_constraint'),
        ),
        migrations.AddConstraint(
            model_name='purchase_product',
            constraint=models.UniqueConstraint(fields=('purchase', 'product'), name='purchase_products_constraint'),
        ),
    ]
