# Generated by Django 5.0.6 on 2024-08-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='offered_total',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
