# Generated by Django 5.0.6 on 2024-08-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_alter_purchase_offered_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
