# Generated by Django 5.0.6 on 2024-08-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_purchase_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
