# Generated by Django 5.0.6 on 2024-08-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_purchase_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_product',
            name='product_offer_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchase_product',
            name='product_total',
            field=models.FloatField(default=0.0),
        ),
    ]
