# Generated by Django 5.0.6 on 2024-08-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_purchase_product_product_offer_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_priceoffer',
            name='offer_total',
            field=models.FloatField(default=0.0),
        ),
    ]
