# Generated by Django 5.0.6 on 2024-08-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0006_purchase_priceoffer_offer_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_priceoffer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase_product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
