# Generated by Django 5.0.6 on 2024-09-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_objecthaspriceoffer_product_offer_constraint'),
        ('purchasing', '0008_purchase_number_of_updates'),
        ('store', '0019_accessories_product_color_size'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchase_priceoffer',
            name='purchase_price_offer_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='purchase_product',
            name='purchase_products_constraint',
        ),
        migrations.AddConstraint(
            model_name='purchase_priceoffer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('purchase', 'price_offer'), name='purchase_price_offer_constraint'),
        ),
        migrations.AddConstraint(
            model_name='purchase_product',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('purchase', 'product'), name='purchase_products_constraint'),
        ),
    ]
