# Generated by Django 5.0.6 on 2024-09-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0009_remove_purchase_priceoffer_purchase_price_offer_constraint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_priceoffer',
            name='unit_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchase_product',
            name='unit_offered_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchase_product',
            name='unit_price',
            field=models.FloatField(default=0.0),
        ),
    ]
