# Generated by Django 5.0.6 on 2024-07-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='points_percentage',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='points',
            name='points',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
