# Generated by Django 5.0.6 on 2024-07-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_points_points_percentage_alter_points_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='points_percentage',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
