# Generated by Django 5.0.6 on 2024-07-26 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_alter_points_points_percentage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
