# Generated by Django 5.0.6 on 2024-09-10 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0029_gym_number_of_rates_trainer_number_of_rates'),
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymrate',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='gym.branch'),
        ),
    ]
