# Generated by Django 5.0.6 on 2024-07-30 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0018_trainer_online_trainine_price_and_more'),
        ('user', '0007_client_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.TimeField(null=True)),
                ('end_hour', models.TimeField(null=True)),
                ('registration_type', models.CharField(max_length=30)),
                ('registration_status', models.CharField(default='pending', max_length=20)),
                ('rejection_reason', models.CharField(max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TraineesRegistrations', to='user.client')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TrainersRegistrations', to='gym.trainer')),
            ],
        ),
    ]
