# Generated by Django 5.0.6 on 2024-07-31 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_client_trainer_end_date_client_trainer_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_trainer',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='client_trainer',
            name='start_date',
        ),
    ]
