# Generated by Django 5.0.6 on 2024-07-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_remove_client_trainer_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_trainer',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='client_trainer',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
