# Generated by Django 5.0.6 on 2024-08-06 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0021_remove_trainer_num_of_trainees_and_more'),
        ('trainer', '0004_client_trainer_end_date_client_trainer_start_date'),
        ('user', '0013_remove_client_wakeup_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('group_capacity', models.PositiveIntegerField(default=0)),
                ('days_on', models.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='client_trainer',
            name='end_hour',
        ),
        migrations.RemoveField(
            model_name='client_trainer',
            name='start_hour',
        ),
        migrations.AlterField(
            model_name='client_trainer',
            name='registration_status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='client_trainer',
            name='registration_type',
            field=models.CharField(choices=[('online', 'online'), ('private', 'private')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='client_trainer',
            constraint=models.UniqueConstraint(condition=models.Q(('registration_status', 'accepted')), fields=('client', 'trainer'), name='client_trainer_registration_status'),
        ),
        migrations.AddField(
            model_name='trainergroups',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='gym.gym'),
        ),
        migrations.AddField(
            model_name='trainergroups',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='gym.trainer'),
        ),
    ]
