# Generated by Django 5.0.6 on 2024-08-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_trainergroups_remove_client_trainer_end_hour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainergroups',
            old_name='days_on',
            new_name='days_off',
        ),
    ]
