# Generated by Django 5.0.6 on 2024-08-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_rename_days_on_trainergroups_days_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainergroups',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
