# Generated by Django 5.0.6 on 2024-08-08 19:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0022_branch_qr_code_image_branch_url'),
        ('trainer', '0007_trainergroups_is_deleted'),
        ('user', '0013_remove_client_wakeup_time'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client_trainer',
            name='client_trainer_registration_status',
        ),
        migrations.AddField(
            model_name='client_trainer',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='trainer.trainergroups'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='client_trainer',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__gte', datetime.date(2024, 8, 8)), ('start_date__lte', datetime.date(2024, 8, 8))), fields=('client', 'trainer'), name='client_trainer_registration_status'),
        ),
    ]
