# Generated by Django 5.0.6 on 2024-08-09 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0022_branch_qr_code_image_branch_url'),
        ('trainer', '0008_remove_client_trainer_client_trainer_registration_status_and_more'),
        ('user', '0014_goal_activity_level_goal_calories_required_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client_trainer',
            name='client_trainer_registration_status',
        ),
        migrations.AddConstraint(
            model_name='client_trainer',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__gte', datetime.date(2024, 8, 9)), ('start_date__lte', datetime.date(2024, 8, 9))), fields=('client', 'trainer'), name='client_trainer_registration_status'),
        ),
    ]
