# Generated by Django 5.0.6 on 2024-08-20 20:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0015_remove_client_trainer_client_trainer_registration_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_trainer',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
