# Generated by Django 5.0.6 on 2024-09-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0019_remove_client_trainer_client_trainer_registration_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client_trainer',
            name='client_trainer_registration_status',
        ),
    ]
