# Generated by Django 5.0.6 on 2024-09-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0020_remove_client_trainer_client_trainer_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_trainer',
            name='old_group_number',
            field=models.IntegerField(null=True),
        ),
    ]
