# Generated by Django 5.0.6 on 2024-09-25 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0030_remove_gym_number_of_rates_remove_gym_rate_and_more'),
        ('trainer', '0021_client_trainer_old_group_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainergroups',
            name='gym',
        ),
        migrations.AddField(
            model_name='trainergroups',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='gym.branch'),
            preserve_default=False,
        ),
    ]
