# Generated by Django 5.0.6 on 2024-08-09 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0022_branch_qr_code_image_branch_url'),
        ('wallet', '0003_rename_amount_wallet_balance_wallet_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet_deposit',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='walletDeposit', to='gym.employee'),
        ),
    ]
