# Generated by Django 5.0.6 on 2024-08-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_wallet_deposit_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet_deposit',
            name='tranasaction_type',
            field=models.CharField(choices=[('cut', 'cut'), ('retrieve', 'retrieve')], default='retrieve', max_length=10),
        ),
    ]
