# Generated by Django 5.0.6 on 2024-08-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_wallet_deposit_tranasaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet_deposit',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
