# Generated by Django 5.0.6 on 2024-08-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_wallet_balance_alter_wallet_deposit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet_deposit',
            name='tranasaction_type',
            field=models.CharField(choices=[('add', 'add'), ('cut', 'cut'), ('retrieve', 'retrieve')], default='retrieve', max_length=10),
        ),
    ]
