# Generated by Django 5.0.6 on 2024-07-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_alter_equipment_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
