# Generated by Django 5.0.6 on 2024-07-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_remove_equipment_qr_code_alter_equipment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
