# Generated by Django 5.0.6 on 2024-07-10 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_equipment_url'),
        ('gym', '0008_gym_allow_public_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to='gym.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Diagrams_Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('x_axis', models.FloatField(default=0.0)),
                ('y_axis', models.FloatField(default=0.0)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='equipments.diagram')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to='equipments.equipment')),
            ],
        ),
    ]
