# Generated by Django 5.0.6 on 2024-07-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_diagram_diagrams_equipments'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagrams_equipments',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
