# Generated by Django 5.0.6 on 2024-07-12 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0007_exercise_equipment_exercise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment_exercise',
            old_name='excercise',
            new_name='exercise',
        ),
    ]
