# Generated by Django 5.0.6 on 2024-07-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0008_rename_excercise_equipment_exercise_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_exercise',
            name='video_path',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
