# Generated by Django 5.0.6 on 2024-07-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0010_remove_equipment_exercise_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_exercise',
            name='video_path',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
