# Generated by Django 5.0.6 on 2024-07-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0014_disease_limitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diagram',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
