# Generated by Django 5.0.6 on 2024-07-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0015_diagram_height_diagram_width'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='equipment_exercise',
            constraint=models.UniqueConstraint(fields=('equipment', 'exercise'), name='unique_exercises_equipments'),
        ),
    ]
