# Generated by Django 5.0.6 on 2024-07-31 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0016_equipment_exercise_unique_exercises_equipments'),
        ('gym', '0018_trainer_online_trainine_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='equipment_exercise',
            name='unique_exercises_equipments',
        ),
        migrations.AddField(
            model_name='equipment_exercise',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='gym.trainer'),
        ),
        migrations.AddConstraint(
            model_name='equipment_exercise',
            constraint=models.UniqueConstraint(fields=('equipment', 'exercise', 'trainer'), name='unique_exercises_equipments'),
        ),
    ]
