# Generated by Django 5.0.6 on 2024-07-31 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0017_remove_equipment_exercise_unique_exercises_equipments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitations',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='limitations',
            name='equipment',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='Limitations',
        ),
    ]
