# Generated by Django 5.0.6 on 2024-08-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0018_remove_limitations_disease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image_path',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
