# Generated by Django 5.0.6 on 2024-08-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0019_equipment_image_path'),
        ('gym', '0018_trainer_online_trainine_price_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='diagram',
            constraint=models.UniqueConstraint(fields=('branch', 'floor'), name='branch_floor'),
        ),
        migrations.AddConstraint(
            model_name='diagrams_equipments',
            constraint=models.UniqueConstraint(fields=('diagram', 'x_axis', 'y_axis'), name='diagram_axises'),
        ),
    ]
