# Generated by Django 5.0.6 on 2024-08-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0020_diagram_branch_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Machines', 'Machines'), ('Free-Weights', 'Free-Weights')], default='Machines', max_length=20),
            preserve_default=False,
        ),
    ]
