# Generated by Django 5.0.6 on 2024-09-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_com', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_posts',
            name='unsaved',
            field=models.BooleanField(default=False),
        ),
    ]
