# Generated by Django 5.0.6 on 2024-09-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_com', '0003_comments_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_replies',
            name='reply',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
