# Generated by Django 5.0.6 on 2024-09-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_com', '0004_comments_replies_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_replies',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
