# Generated by Django 5.0.6 on 2024-07-01 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shifts',
            old_name='day_of_week',
            new_name='Shift_type',
        ),
        migrations.RemoveField(
            model_name='shifts',
            name='end_hour',
        ),
        migrations.RemoveField(
            model_name='shifts',
            name='start_hour',
        ),
    ]
