# Generated by Django 5.0.6 on 2024-07-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_rename_day_of_week_shifts_shift_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
