# Generated by Django 5.0.6 on 2024-07-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_shifts_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifts',
            name='days_off',
            field=models.JSONField(default={}),
        ),
    ]
