# Generated by Django 5.0.6 on 2024-07-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_alter_shifts_days_off'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shifts',
            old_name='Shift_type',
            new_name='shift_type',
        ),
    ]
