# Generated by Django 5.0.6 on 2024-07-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_rename_shift_type_shifts_shift_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifts',
            name='shift_type',
            field=models.CharField(max_length=50),
        ),
    ]
