# Generated by Django 5.0.6 on 2024-07-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_gym_allow_public_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='allow_public_products',
            field=models.BooleanField(default=True),
        ),
    ]
