# Generated by Django 5.0.6 on 2024-07-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_branch_city_branch_street_registration_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='regestration_price',
        ),
    ]
