# Generated by Django 5.0.6 on 2024-07-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_remove_gym_regestration_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='quit_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='start_date',
        ),
    ]
