# Generated by Django 5.0.6 on 2024-07-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_remove_employee_quit_date_remove_employee_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='num_of_trainees',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
