# Generated by Django 5.0.6 on 2024-07-19 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0014_employee_allow_public_posts_for_trainers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='allow_public_posts_for_trainers',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='num_of_trainees',
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_trainees', models.IntegerField(default=0)),
                ('allow_public_posts', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='gym.employee')),
            ],
        ),
    ]
