# Generated by Django 5.0.6 on 2024-07-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0015_remove_employee_allow_public_posts_for_trainers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='allowed_days_for_registraiton_cancellation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gym',
            name='current_number_of_clients',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gym',
            name='number_of_clients_allowed',
            field=models.IntegerField(default=0),
        ),
    ]
