# Generated by Django 5.0.6 on 2024-07-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0016_gym_allowed_days_for_registraiton_cancellation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='session_period',
            field=models.IntegerField(default=0),
        ),
    ]
