# Generated by Django 5.0.6 on 2024-08-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0018_trainer_online_trainine_price_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registration_fee',
            constraint=models.UniqueConstraint(fields=('gym', 'type'), name='gym_type'),
        ),
    ]
