# Generated by Django 5.0.6 on 2024-08-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0019_registration_fee_gym_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='online_trainine_price',
            new_name='online_training_price',
        ),
    ]
