# Generated by Django 5.0.6 on 2024-08-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0020_rename_online_trainine_price_trainer_online_training_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='num_of_trainees',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='session_period',
        ),
    ]
