# Generated by Django 5.0.6 on 2024-08-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0021_remove_trainer_num_of_trainees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
        migrations.AddField(
            model_name='branch',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
