# Generated by Django 5.0.6 on 2024-08-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0022_branch_qr_code_image_branch_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='allow_branches_access',
            field=models.BooleanField(default=False),
        ),
    ]
