# Generated by Django 5.0.6 on 2024-08-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0023_gym_allow_branches_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_fee',
            name='type',
            field=models.CharField(choices=[('daily', 'daily'), ('15_days', '15_days'), ('monthly', 'monthly'), ('3_months', '3_months'), ('6_months', '6_months'), ('yearly', 'yearly')], max_length=50),
        ),
    ]
