# Generated by Django 5.0.6 on 2024-08-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0024_alter_registration_fee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_fee',
            name='type',
            field=models.CharField(choices=[('1_day', '1_day'), ('15_days', '15_days'), ('monthly', 'monthly'), ('3_months', '3_months'), ('6_months', '6_months'), ('yearly', 'yearly')], max_length=50),
        ),
    ]
