# Generated by Django 5.0.6 on 2024-08-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0025_alter_registration_fee_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='current_number_of_clients',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='number_of_clients_allowed',
        ),
        migrations.AddField(
            model_name='branch',
            name='current_number_of_clients',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='number_of_clients_allowed',
            field=models.IntegerField(default=0),
        ),
    ]
