# Generated by Django 5.0.6 on 2024-08-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0026_remove_gym_current_number_of_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='allowed_number_for_update',
            field=models.IntegerField(default=0),
        ),
    ]
