# Generated by Django 5.0.6 on 2024-09-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0027_gym_allowed_number_for_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trainer',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
