# Generated by Django 5.0.6 on 2024-09-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0028_gym_rate_trainer_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='number_of_rates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainer',
            name='number_of_rates',
            field=models.IntegerField(default=0),
        ),
    ]
