# Generated by Django 5.0.6 on 2024-09-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0029_gym_number_of_rates_trainer_number_of_rates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='number_of_rates',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='rate',
        ),
        migrations.AddField(
            model_name='branch',
            name='number_of_rates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
